version: "3.8"

services:
  jistargram-client:
    build: ./jistargram-client
    volumes:
      - ./jistargram-client:/app
      - /app/node_modules
    ports:
      - "3000:80"
    depends_on:
      - jistargram-server

  jistargram-server:
    build: ./jistargram-server
    volumes:
      - ./jistargram-server/public/uploads/post_imgs:/app/public/uploads/post_imgs
      - ./jistargram-server/public/uploads/profile_imgs:/app/public/uploads/profile_imgs
    ports:
      - "4000:4000"
    env_file:
      - ./jistargram-server/.env
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    env_file:
      - ./jistargram-server/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./jistargram-server/sql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
