services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - jistargram-client
      - jistargram-server

  jistargram-client:
    build: 
      context: ./jistargram-client
      args:
        - REACT_APP_API_URL=/api
    depends_on:
      - jistargram-server

  jistargram-server:
    build: ./jistargram-server
    volumes:
      - ./jistargram-server/public/uploads/post_imgs:/app/public/uploads/post_imgs
      - ./jistargram-server/public/uploads/profile_imgs:/app/public/uploads/profile_imgs
    env_file:
      - .env.docker
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    restart: always
    env_file:
      - ./.env.docker
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./jistargram-server/migration/0000_init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:alpine
    restart: always

volumes:
  pgdata:
